### ISSUE TITLE
error moving backup

### ISSUE THREAD

**Issue by tihe** [woxxy/MySQL-backup-to-Amazon-S3#7]
At the line of moving the backup from day to previous day I get the below errors. Result is that the old backup is moved to /previous_day but it also still shows up in /day. Apparently the delete part of the mv command fails.

Moving the backup from past day to another folder...
WARNING: Retrying failed request: /sql/previous_day/databases.03.26.2013.tar.gz (timed out)
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: /sql/previous_day/databases.03.26.2013.tar.gz (timed out)
WARNING: Waiting 6 sec...
WARNING: Retrying failed request: /sql/previous_day/databases.03.26.2013.tar.gz (timed out)
WARNING: Waiting 9 sec...
WARNING: Retrying failed request: /sql/previous_day/databases.03.26.2013.tar.gz (timed out)
WARNING: Waiting 12 sec...
WARNING: Retrying failed request: /sql/previous_day/databases.03.26.2013.tar.gz (timed out)
WARNING: Waiting 15 sec...

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please report the following lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Problem: S3RequestError: Request failed for: /sql/previous_day/databases.03.26.2013.tar.gz
S3cmd:   1.0.0

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2006, in <module>
    main()
  File "/usr/bin/s3cmd", line 1950, in main
    cmd_func(args)
  File "/usr/bin/s3cmd", line 618, in cmd_mv
    subcmd_cp_mv(args, s3.object_move, "move", "File %(src)s moved to %(dst)s")
  File "/usr/bin/s3cmd", line 607, in subcmd_cp_mv
    response = process_fce(src_uri, dst_uri, extra_headers)
  File "/usr/share/s3cmd/S3/S3.py", line 315, in object_move
    response_copy = self.object_copy(src_uri, dst_uri, extra_headers)
  File "/usr/share/s3cmd/S3/S3.py", line 311, in object_copy
    response = self.send_request(request)
  File "/usr/share/s3cmd/S3/S3.py", line 487, in send_request
    return self.send_request(request, body, retries - 1)
  File "/usr/share/s3cmd/S3/S3.py", line 487, in send_request
    return self.send_request(request, body, retries - 1)
  File "/usr/share/s3cmd/S3/S3.py", line 487, in send_request
    return self.send_request(request, body, retries - 1)
  File "/usr/share/s3cmd/S3/S3.py", line 487, in send_request
    return self.send_request(request, body, retries - 1)
  File "/usr/share/s3cmd/S3/S3.py", line 487, in send_request
    return self.send_request(request, body, retries - 1)
  File "/usr/share/s3cmd/S3/S3.py", line 489, in send_request
    raise S3RequestError("Request failed for: %s" % resource['uri'])
S3RequestError: Request failed for: /sql/previous_day/databases.03.26.2013.tar.gz

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
    Please report the above lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Past backup moved.

**Comment by codex73** [comment]
@tihe what does your cronjob look like? Do you still have this issue?
